variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REGISTRY: nexus.ci.psu.edu:5000
  REGISTRY_NAMESPACE: swe
  GIT_UTILS_IMAGE: quay.io/dannbohn/git-utils:latest

stages:
- release
- build

.release: &release
  variables: &release_vars
    CI_REPOSITORY_URL: https://aitci:$GITLAB_AUTH_TOKEN@git.psu.edu/$CI_PROJECT_PATH.git
  stage: release
  image: quay.io/dannbohn/git-utils:latest
  except:
  - tags
  script:
  - bumpver -p v $BUMP_TYPE
  - git push --tags $CI_REPOSITORY_URL -q

release_minor:
  <<: *release
  variables:
    <<: *release_vars
    BUMP_TYPE: minor
  only:
  - develop

release_major:
  <<: *release
  variables:
    <<: *release_vars
    BUMP_TYPE: major
  only:
  - master


build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  only:
  - tags
  script:
  - docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
  - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
  - docker tag $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:latest
  - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME


